language: csharp
jobs:
  include:
  - os: linux
    dotnet: 3.1.101
    mono: none
  - os: osx
    osx_image: xcode11
    dotnet: 3.1.101
    mono: none
script:
- dotnet restore ./src/Vlingo.Lattice.sln; dotnet build ./src/Vlingo.Lattice.sln;
  dotnet test ./src/Vlingo.Lattice.Tests/Vlingo.Lattice.Tests.csproj;
notifications:
  slack:
    secure: oMZUBSiiaiVZQR8BXHMNaZaQbyrzh6xkKT7wikhpL4px6mTt/emurCrH28/BtFV5tP0m7P9CqQHlzzHP3DcyevPd19H1IanpZJnEiw9osNgoLj8qRKT2R0m7GFQqOJH2UuFI7sfagn+YLE9ZM2K0sbSBjY26RLLnKcmDIU2/28INzDzeR5zHHfONaz0GYpnS9k2U9DACzAiVErVXRC15vTjTpCQZKvZm2k3MROOgGAyd34eCSeZe95kDFTB84hVoIvmuBR+2/WtJlbBncVdFu/HL2S+pQuT2r97ChTXD2GnZ0dcbE8Ii0m9X2lrdM0Nt1w+YsuuuD6YF8ayRneQYTlinimZMkFCGRfFzj42627lHHAYMiKUYZ7Nn5DI7YalFslN4NCmHHzlQ7pg6N1L7RyYsyWHF9oUcndH59/22gCvBYPUrLlNpNP16C9ycnbecuJjwIegLlYReVggxsohS4aVNPb60YtCuiD1q3oLH57foOfl+u/x36P4lZPVvTT9Xn0cOZtl3wTL/KlSVfYX2ZB/nh6HHw3vZDuZHPpVl2jLZe1FlGe78o344k+LoE0cnwrkJ6hycOAdSM8IlBDxPMiywvcjnvdTt33wHr6rIlq5LgILHvm0Nyg1O/uRsdb4Buae9bxi4OJL/wTEOYsA2F/d0idx2URc50DUsADBPj5U=
